services:
  redis:
    image: redis:7
    container_name: review_redis

  review_app:
    image: review_image
    build:
      context: .
    env_file:
      - .env
    container_name: review_app
    depends_on:
      redis:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    command: ["/auto_app/docker/app.sh"]
    ports:
      - 8001:8001

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  grafanadata:
  prometheusdata: